import type { SmartCitySource } from "./types";

export const THAILAND_SOURCES: SmartCitySource[] = [
  {
    id: "bma-traffic",
    name: "Bangkok traffic and transport references",
    provider: "Bangkok Metropolitan Administration",
    category: "traffic",
    region: "bangkok",
    sourceUrl: "https://traffic.bangkok.go.th/AboutUS/dev.html",
    refreshSeconds: 300,
    dataClass: "needs_config",
    refreshPolicy: "reference page until feed URL is configured",
    upstreamCadence: "not a live API",
  },
  {
    id: "doh-travel",
    name: "DOH to Travel road signals",
    provider: "Department of Highways",
    category: "road_status",
    region: "thailand",
    sourceUrl: "https://www.thailand.go.th/public/issue-focus-detail/001_08_028",
    refreshSeconds: 300,
    dataClass: "near_real_time",
    refreshPolicy: "external service reference",
    upstreamCadence: "road-status service",
  },
  {
    id: "itic-live-events",
    name: "iTIC / Longdo live traffic events",
    provider: "iTIC Foundation / Longdo Traffic",
    category: "live_incident",
    region: "thailand",
    sourceUrl: "https://event.longdo.com/feed/json",
    refreshSeconds: 300,
    dataClass: "live",
    refreshPolicy: "request-time fetch with short read-model cache",
    upstreamCadence: "live event feed",
  },
  {
    id: "itic-open-data",
    name: "iTIC historical traffic and incident data",
    provider: "iTIC Foundation",
    category: "incident_archive",
    region: "thailand",
    sourceUrl: "https://itic.longdo.com/data/",
    refreshSeconds: 3600,
    dataClass: "historical",
    refreshPolicy: "archive pull when configured",
    upstreamCadence: "archive",
  },
  {
    id: "data-goth-traffic",
    name: "Open Government traffic datasets",
    provider: "Open Government Data of Thailand",
    category: "open_data",
    region: "thailand",
    sourceUrl: "https://www.data.go.th/th/dataset/index-traffic",
    refreshSeconds: 86400,
    dataClass: "official_baseline",
    refreshPolicy: "CKAN official dataset",
    upstreamCadence: "dataset publication cadence",
  },
];
